installer_checksums:
  Miniconda3-latest-Linux-x86_64.sh: 'bfe34e1fa28d6d75a7ad05fd02fa5472275673d5f5621b77380898dee1be15d2'
  Miniconda3-4.7.12.1-Linux-x86_64.sh: 'bfe34e1fa28d6d75a7ad05fd02fa5472275673d5f5621b77380898dee1be15d2'
  Anaconda3-2019.10-Linux-x86_64.sh: '46d762284d252e51cd58a8ca6c8adc9da2eadc82c342927b2f66ed011d1d8b53'
environments:
  - name: miniconda3
    version: '4.7.12.1'
    miniconda: True
    python_version: 3
    installer_version: '4.7.12.1'
    condarc:
      channels:
        - defaults
  - name: anaconda
    version: '2020-01-tf1'
    miniconda: False
    python_version: 3
    installer_version: '2019.10'
    condarc:
      channels:
        - defaults
        - pytorch
        - gurobi
        - IBMDecisionOptimization
        - anaconda
        - brainiak
        - conda-forge
    pip_packages:
        - bash-kernel
        - cdlib
        - demon
        - docopt
        - gym
        - leidenalg
        - matlab-kernel
        - mne
        - nf1
        - numpy
        - omega-index-py3
        - pquality
        - pulp
        - pyglet
        - pymanopt
        - pymvpa2
        - python-igraph
        - python-louvain
        - roboschool
        - sphinx
        - sphinx-rtd-theme
        - tqdm
    conda_packages:
        - absl-py
        - alabaster
        - anaconda
        - anaconda-client
        - anaconda-navigator
        - anaconda-project
        - appdirs
        - asn1crypto
        - astor
        - astroid
        - astropy
        - atomicwrites
        - attrs
        - automat
        - babel
        - backcall
        - backports
        - backports.os
        - backports.shutil_get_terminal_size
        - backports.weakref
        - bcolz
        - bcrypt
        - beautifulsoup4
        - binutils_impl_linux-64
        - binutils_linux-64
        - bitarray
        - bkcharts
        - blas
        - blaze
        - bleach
        - blosc
        - bokeh
        - boto
        - boto3
        - botocore
        - bottleneck
        - brainiak
        - bz2file
        - bzip2
        - c-ares
        - ca-certificates
        - cairo
        - certifi
        - cffi
        - chardet
        - click
        - cloudpickle
        - clyent
        - colorama
        - conda
        - conda-env
        - conda-package-handling
        - constantly
        - contextlib2
        - coverage
        - cplex
        - cryptography
        - cryptography-vectors
        - cuda100
        - cudatoolkit
        - cudnn
        - cupti
        - curl
        - cycler
        - cython
        - cytoolz
        - dask
        - dask-core
        - datashape
        - dbus
        - decorator
        - defusedxml
        - dill
        - distributed
        - docutils
        - entrypoints
        - et_xmlfile
        - expat
        - fastcache
        - flask
        - flask-cors
        - fontconfig
        - freetype
        - fribidi
        - future
        - gast
        - gcc_impl_linux-64
        - gcc_linux-64
        - gensim
        - get_terminal_size
        - gevent
        - glib
        - gmp
        - gmpy2
        - gpy
        - graphite2
        - greenlet
        - grpcio
        - gst-plugins-base
        - gstreamer
        - gurobi
        - gxx_impl_linux-64
        - gxx_linux-64
        - h5py
        - harfbuzz
        - hdf4
        - hdf5
        - heapdict
        - html5lib
        - hyperlink
        - hypothesis
        - icu
        - idna
        - imageio
        - imagesize
        - importlib_metadata
        - incremental
        - intel-openmp
        - ipykernel
        - ipyparallel
        - ipython
        - ipython_genutils
        - ipywidgets
        - isort
        - itsdangerous
        - jbig
        - jdcal
        - jedi
        - jeepney
        - jinja2
        - jmespath
        - joblib
        - jpeg
        - jsoncpp
        - jsonschema
        - jupyter
        - jupyter_client
        - jupyter_console
        - jupyter_core
        - jupyterlab
        - jupyterlab_server
        - keras
        - keras-applications
        - keras-base
        - keras-preprocessing
        - keyring
        - kiwisolver
        - krb5
        - lazy-object-proxy
        - libarchive
        - libcurl
        - libedit
        - libffi
        - libgcc
        - libgcc-ng
        - libgfortran
        - libgfortran-ng
        - libgpuarray
        - libiconv
        - libnetcdf
        - libogg
        - libpng
        - libprotobuf
        - libsodium
        - libssh2
        - libstdcxx-ng
        - libtheora
        - libtiff
        - libtool
        - libuuid
        - libvorbis
        - libxcb
        - libxgboost
        - libxml2
        - libxslt
        - llvm-openmp
        - llvmlite
        - locket
        - lxml
        - lz4-c
        - lzo
        - mako
        - markdown
        - markupsafe
        - matplotlib
        - mccabe
        - metakernel
        - mistune
        - mkl
        - mkl-service
        - mkl_fft
        - mkl_random
        - mock
        - more-itertools
        - mpc
        - mpfr
        - mpi4py
        - mpich2
        - mpmath
        - msgpack-python
        - multipledispatch
        - navigator-updater
        - nbconvert
        - nbformat
        - nccl
        - ncurses
        - networkx
        - nibabel
        - ninja
        - nitime
        - nltk
        - nose
        - notebook
        - numba
        - numexpr
        - numpy-base
        - numpydoc
        - odo
        - olefile
        - openmp
        - openpyxl
        - openssl
        - packaging
        - pandas
        - pandoc
        - pandocfilters
        - pango
        - paramz
        - parso
        - partd
        - path.py
        - pathlib2
        - patsy
        - pbr
        - pcre
        - pep8
        - pexpect
        - phonopy
        - pickleshare
        - pillow
        - pip
        - pixman
        - plotly
        - pluggy
        - ply
        - prometheus_client
        - prompt_toolkit
        - protobuf
        - psutil
        - ptyprocess
        - py
        - py-xgboost
        - pyasn1
        - pyasn1-modules
        - pybind11
        - pycodestyle
        - pycosat
        - pycparser
        - pycrypto
        - pycurl
        - pydicom
        - pyflakes
        - pygments
        - pygpu
        - pyhamcrest
        - pylint
        - pympler
        - pyodbc
        - pyopenssl
        - pyparsing
        - pyqt
        - pyrsistent
        - pysocks
        - pytables
        - pytest
        - pytest-arraydiff
        - pytest-astropy
        - pytest-doctestplus
        - pytest-openfiles
        - pytest-remotedata
        - python
        - python-dateutil
        - python-libarchive-c
        - pytorch
        - pytz
        - pywavelets
        - pyyaml
        - pyzmq
        - qt
        - qtawesome
        - qtconsole
        - qtpy
        - readline
        - requests
        - retrying
        - rope
        - ruamel_yaml
        - s3transfer
        - scikit-image
        - scikit-learn
        - seaborn
        - secretstorage
        - send2trash
        - service_identity
        - setuptools
        - simplegeneric
        - singledispatch
        - sip
        - six
        - smart_open
        - snappy
        - snowballstemmer
        - sortedcollections
        - sortedcontainers
        - soupsieve
        - sphinxcontrib
        - sphinxcontrib-applehelp
        - sphinxcontrib-devhelp
        - sphinxcontrib-htmlhelp
        - sphinxcontrib-jsmath
        - sphinxcontrib-qthelp
        - sphinxcontrib-serializinghtml
        - sphinxcontrib-websupport
        - spyder
        - spyder-kernels
        - sqlalchemy
        - sqlite
        - statsmodels
        - sympy
        - tbb
        - tblib
        - tensorboard
        - tensorflow=1.15.0
        - tensorflow-base
        - tensorflow-estimator
        - tensorflow-gpu
        - termcolor
        - terminado
        - testpath
        - theano
        - tk
        - toolz
        - torchvision
        - tornado
        - traitlets
        - twisted
        - typed-ast
        - typing
        - unicodecsv
        - unixodbc
        - urllib3
        - vtk
        - wcwidth
        - webencodings
        - werkzeug
        - wheel
        - widgetsnbextension
        - wrapt
        - wurlitzer
        - xgboost
        - xlrd
        - xlsxwriter
        - xlwt
        - xz
        - yaml
        - zeromq
        - zict
        - zipp
        - zlib
        - zope
        - zope.interface
        - zstd
