config:
  install_path: /cvmfs/fgi.csc.fi/apps/el7/aalto/anaconda/software
  module_path: /cvmfs/fgi.csc.fi/apps/el7/aalto/anaconda/modules
  source_cache: /cache/anaconda
  tmpdir: /tmp/anaconda
  remove_after_update: True
