packages:
  autoconf:
    paths:
      autoconf: /fake/path
    buildable: False
  automake:
    paths:
      automake: /fake/path
    buildable: False
  cmake:
    paths:
      cmake: /fake/path
    buildable: False
  flex:
    paths:
      flex: /fake/path
    buildable: False
  libtool:
    paths:
      libtool: /fake/path
    buildable: False
  m4:
    paths:
      m4: /fake/path
    buildable: False
  zlib:
    paths:
      zlib: /fake/path
    buildable: False
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag]
    providers:
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      gl: [mesa, opengl]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [jdk]
      lapack: [openblas]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [openmpi, mpich]
      opencl: [pocl]
      openfoam: [openfoam-com, openfoam-org, foam-extend]
      pil: [py-pillow]
      pkgconfig: [pkgconf, pkg-config]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      jpeg: [libjpeg-turbo, libjpeg]
