name: buildrules
channels:
  - defaults
dependencies:
  - _libgcc_mutex
  - alabaster
  - asn1crypto
  - astroid
  - attrs
  - babel
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - coloredlogs
  - conda
  - conda-package-handling
  - cryptography
  - docutils
  - humanfriendly
  - idna
  - imagesize
  - isort
  - jinja2
  - jsonschema
  - lazy-object-proxy
  - libarchive
  - libedit
  - libffi
  - libgcc-ng
  - libstdcxx-ng
  - libxml2
  - lz4-c
  - lzo
  - markupsafe
  - mccabe
  - ncurses
  - openssl
  - packaging
  - pip
  - pycosat
  - pycparser
  - pygments
  - pylint
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - python
  - python-libarchive-c
  - pytz
  - pyyaml
  - readline
  - requests
  - ruamel_yaml
  - setuptools
  - sh
  - six
  - snowballstemmer
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sqlite
  - testfixtures
  - tk
  - tqdm
  - urllib3
  - wheel
  - wrapt
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
    - j2cli
    - jinja2-cli
