name: buildrules
channels:
  - defaults
dependencies:
  - alabaster
  - asn1crypto
  - astroid
  - attrs
  - babel
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - coloredlogs
  - conda
  - cryptography
  - docutils
  - idna
  - imagesize
  - ipython
  - isort
  - jinja2
  - jsonschema
  - lazy-object-proxy
  - libedit
  - libffi
  - libgcc-ng
  - libstdcxx-ng
  - markupsafe
  - mccabe
  - ncurses
  - openssl
  - packaging
  - pip
  - pycosat
  - pycparser
  - pygments
  - pylint
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - python>=3.7
  - pytz
  - pyyaml
  - readline
  - requests
  - ruamel_yaml
  - setuptools
  - six
  - snowballstemmer
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sqlite
  - testfixtures
  - tk
  - urllib3
  - wheel
  - wrapt
  - xz
  - yaml
  - zlib
