FROM ubuntu:22.04 as base_image

ARG DEBIAN_FRONTEND=noninteractive

USER root

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
  apt-transport-https                     \
  bash                                    \
  bash-completion                         \
  ca-certificates                         \
  cmake                                   \
  cpio                                    \
  curl                                    \
  git                                     \
  grep                                    \
  locales                                 \
  libarchive-dev                          \
  libnl-3-200                             \
  libnl-3-dev                             \
  libssh-4                                \
  libssh2-1                               \
  libssh2-1-dev                           \
  libssl-dev                              \
  libvshadow-utils                        \
  lmod                                    \
  openssh-client                          \
  python-is-python3                       \
  python3                                 \
  python3-dev                             \
  rustc                                   \
  rsync                                   \
  software-properties-common              \
  squashfs-tools                          \
  ssh                                     \
  sudo                                    \
  swig                                    \
  tcl                                     \
  unzip                                   \
  uuid-dev                                \
  wget                                    \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
  libgl1-mesa-dri                         \
  xbitmaps                                \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
  build-essential                         \
  libssl-dev                              \
  uuid-dev                                \
  libgpgme-dev                            \
  squashfs-tools                          \
  libseccomp-dev                          \
  wget                                    \
  pkg-config                              \
  git                                     \
  cryptsetup-bin                          \
  && rm -rf /var/lib/apt/lists/*

# Install apptainer

RUN add-apt-repository -y ppa:apptainer/ppa && \
  apt-get update &&                            \
  apt-get install -y                           \
  apptainer                                    \
  apptainer-suid                               \
  && rm -rf /var/lib/apt/lists/*

RUN echo 'buildbot ALL=(ALL) NOPASSWD:SETENV: /usr/bin/singularity, /usr/bin/apptainer, /bin/chown' >> /etc/sudoers

# Fix gosu gpg key import error
RUN mkdir ~/.gnupg
RUN echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf

RUN apt-get update &&                     \
  apt-get -y install -q                   \
  python3-pip                             \
  && rm -rf /var/lib/apt/lists/*

# Add locale for en_US.UTF-8
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen

FROM ubuntu:22.04 as cuda
COPY --from=base_image / /

# Add NVIDIA CUDA driver
RUN apt-get update &&                          \
  apt-get install -y kmod                      \
  && rm -rf /var/lib/apt/lists/*

ENV RUNFILE_DIR=/runfile
ARG CUDA_DRIVER_VERSION=525.85.12
ENV CUDA_DRIVER_RUNFILE=NVIDIA-Linux-x86_64-${CUDA_DRIVER_VERSION}.run

RUN mkdir ${RUNFILE_DIR}
COPY ./extras/${CUDA_DRIVER_RUNFILE} ${RUNFILE_DIR}

RUN bash ${RUNFILE_DIR}/${CUDA_DRIVER_RUNFILE} --silent --no-kernel-module && \
  rm -rf ${RUNFILE_DIR}

FROM ubuntu:22.04

COPY --from=cuda / /

{% include 'common/Dockerfile.j2' %}
