command_collections:
  common:
    post_commands:
      - 'mkdir -p /my_mount'
flag_collections:
  common:
    - '-B /tmp:/my_mount'
  nvidia:
    - '--nv'
definitions:
  - name: singularity-ubuntu
    docker_user: library
    docker_image: ubuntu
    tags:
      - 'latest'
    flag_collections:
      - 'common'
    command_collections:
      - 'common'
  - name: singularity-tensorflow
    docker_user: tensorflow
    docker_image: tensorflow
    tags:
      - 'latest'
    flag_collections:
      - 'common'
      - 'nvidia'
    command_collections:
      - 'common'
