command_collections:
  common:
    post_commands:
      - 'mkdir -p /my_mount'
flag_collections:
  common:
    - '-B /tmp:/my_mount'
definitions:
  - name: ubuntu
    docker_user: library
    docker_image: ubuntu
    tags:
      - 'latest'
    flag_collections:
      - 'common'
    command_collections:
      - 'common'
