config:
  install_path: $singularity/opt/singularity/software
  module_path: $singularity/opt/singularity/modules
  source_cache: $singularity/var/singularity/cache
  tmpdir: $singularity/var/singularity/tmpdir
  build_stage: $singularity/var/singularity/stage
  wrapper_path: $singularity/opt/singularity/bin
  remove_after_update: True
  sudo: False
  fakeroot: True
  debug: False
