# Install gosu
RUN set -eux; \
    gpg --keyserver ipv4.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
    && curl -o /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/1.2/gosu-amd64" \
    && curl -o /usr/local/bin/gosu.asc -SL "https://github.com/tianon/gosu/releases/download/1.2/gosu-amd64.asc" \
    && gpg --verify /usr/local/bin/gosu.asc \
    && rm /usr/local/bin/gosu.asc \
    && rm -r /root/.gnupg/ \
    && chmod +x /usr/local/bin/gosu \
	  && gosu nobody true

# Install dumb-init
RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.1/dumb-init_1.2.1_amd64 && \
echo "057ecd4ac1d3c3be31f82fc0848bf77b1326a975b4f8423fe31607205a0fe945  /usr/local/bin/dumb-init" | sha256sum -c - && \
chmod 755 /usr/local/bin/dumb-init

# Install more requirements
RUN pip3 --no-cache-dir install twisted[tls] && \
  mkdir /buildbot && \
  useradd -ms /bin/bash buildbot

# Setting buildbot version
ARG BUILDBOT_VERSION=v2.4.0

# Clone buildbot repo
RUN git clone https://github.com/buildbot/buildbot.git /usr/src/buildbot && \
  cd /usr/src/buildbot/worker && \
  git checkout $BUILDBOT_VERSION && \
  cp docker/buildbot.tac /buildbot/buildbot.tac

# Install buildbot
RUN pip3 install /usr/src/buildbot/worker && \
  chown -Rh buildbot.buildbot /buildbot

# Copy builder scripts

COPY ./common/bin/build-anaconda.sh /usr/local/bin/build-anaconda
RUN  chmod +x /usr/local/bin/build-anaconda

COPY ./common/bin/build-singularity.sh /usr/local/bin/build-singularity
RUN  chmod +x /usr/local/bin/build-singularity

COPY ./common/bin/build-spack.sh /usr/local/bin/build-spack
RUN  chmod +x /usr/local/bin/build-spack

COPY ./common/bin/spackbuilder.sh /usr/local/bin/spackbuilder
RUN  chmod +x /usr/local/bin/spackbuilder

COPY ./common/entry.sh /usr/local/bin/entry.sh
RUN  chmod +x /usr/local/bin/entry.sh

ENTRYPOINT ["/usr/local/bin/entry.sh"]
WORKDIR /buildbot
CMD ["/usr/local/bin/dumb-init", "twistd", "-ny", "buildbot.tac"]

USER root
