compilers:
  - name: 'gcc'
    version: 4.8.5
    system_compiler: true
    flags:
      cflags: -O2 -g
      cxxflags: -O2 -g
      cppflags: -O2 -g
      fflags: -O2 -g
packages:
  - name: libtool
    version: 2.4.6
