compilers:
  - name: 'gcc'
    version: 5.5.0
    dependencies:
      - '%gcc@4.8.5'
    flags:
      cflags: -O2 -fPIC
      cxxflags: -O2 -fPIC
      cppflags: -O2 -fPIC
      fflags: -O2 -fPIC
packages:
  - name: libtool
    version: 2.4.6
  - name: 'openmpi'
    version: 2.1.2
    variants:
      - "fabrics=verbs"
      - "schedulers=slurm"
      - "+pmi"
      - "+thread_multiple"
  - name: 'openmpi'
    version: 2.1.5
    variants:
      - "fabrics=verbs"
      - "schedulers=slurm"
      - "+pmi"
      - "+thread_multiple"
  - name: 'bison'
    version: 3.0.5
  - name: 'clhep'
    version: 2.4.0.0
