config:
  install_tree: /share/apps/spack/production/software
  install_path_scheme: '${PACKAGE}/${VERSION}/${HASH:7}'
  module_roots:
    tcl: /share/apps/spack/production/modules
    lmod: /share/apps/spack/production/lmod
    dotkit: /share/apps/spack/production/dotkit
  source_cache: /cache
  misc_cache: /tmp/spack_misc_cache
  build_stage:
    - $spack/var/spack/stage
  locks: false
