modules:
  enable:
    - lmod
  prefix_inspections:
    bin:
      - PATH
    man:
      - MANPATH
    share/man:
      - MANPATH
    share/aclocal:
      - ACLOCAL_PATH
    lib:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    lib64:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    include:
      - CPATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH
  lmod:
    whitelist:
      - 'gcc'
    blacklist: []
    core_compilers:
      - 'gcc@4.8.5'
    hash_length: 0
    all:
      autoload: 'direct'
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'
      suffixes: {}
    gcc:
      environment:
        prepend_path:
          LIBRARY_PATH: '${PREFIX}/lib/gcc/x86_64-unknown-linux-gnu/${VERSION}'
          LD_LIBRARY_PATH: '${PREFIX}/lib/gcc/x86_64-unknown-linux-gnu/${VERSION}'
