installer_checksums:
  'Miniconda3-latest-Linux-x86_64.sh': '8a324adcc9eaf1c09e22a992bb6234d91a94146840ee6b11c114ecadafc68121'
environments:
  - name: miniconda
    version: latest
    miniconda: True
    python_version: 3
    installer_version: latest
