FROM centos:centos7

RUN yum install -y epel-release           \
  && yum update -y                        \
  && yum clean all

RUN yum groups mark install "Development Tools" \
  && yum groups mark convert "Development Tools" \
  && yum groupinstall -y "Development Tools" \
  && yum clean all

# Base dependencies
RUN yum update -y && yum install -y       \
  Lmod                                    \
  bash-completion                         \
  cmake                                   \
  curl                                    \
  git                                     \
  libarchive-devel                        \
  libnl3                                  \
  libnl3-devel                            \
  libuuid-devel                           \
  openssh                                 \
  openssl-devel                           \
  python                                  \
  python-devel                            \
  python36                                \
  python36-devel                          \
  rust                                    \
  rsync                                   \
  shadow-utils                            \
  squashfs-tools                          \
  sudo                                    \
  tcl                                     \
  unzip                                   \
  wget                                    \
  which                                   \
  && yum clean all

# Install singularity

RUN yum update -y && yum install -y       \
  singularity                             \
  && yum clean all

# Add Open HPC slurm

ARG TARGET

RUN yum install -y https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm

RUN yum update -y && yum install -y       \
  hwloc-libs                              \
  munge-ohpc                              \
  pmix                                    \
  pmix-devel                              \
  libibverbs                              \
  libibverbs-devel                        \
  && yum clean all

ENV SLURM_DIR=/tmp/rpms

ARG SLURM_VERSION=21.08.0-4.1
ARG OHPC_VERSION=1.3.8.1

COPY ./extra_rpms $SLURM_DIR

RUN yum localinstall -y                   \
  ${SLURM_DIR}/slurm-contribs-ohpc-${SLURM_VERSION}.ohpc.${OHPC_VERSION}.x86_64.rpm        \
  ${SLURM_DIR}/slurm-devel-ohpc-${SLURM_VERSION}.ohpc.${OHPC_VERSION}.x86_64.rpm           \
  ${SLURM_DIR}/slurm-example-configs-ohpc-${SLURM_VERSION}.ohpc.${OHPC_VERSION}.x86_64.rpm \
  ${SLURM_DIR}/slurm-libpmi-ohpc-${SLURM_VERSION}.ohpc.${OHPC_VERSION}.x86_64.rpm          \
  ${SLURM_DIR}/slurm-ohpc-${SLURM_VERSION}.ohpc.${OHPC_VERSION}.x86_64.rpm                 \
  ${SLURM_DIR}/slurm-pam_slurm-ohpc-${SLURM_VERSION}.ohpc.${OHPC_VERSION}.x86_64.rpm       \
  ${SLURM_DIR}/slurm-perlapi-ohpc-${SLURM_VERSION}.ohpc.${OHPC_VERSION}.x86_64.rpm         \
  ${SLURM_DIR}/slurm-slurmd-ohpc-${SLURM_VERSION}.ohpc.${OHPC_VERSION}.x86_64.rpm          \
  && yum clean all

# Add other packages

RUN yum update -y && yum install -y       \
  mesa-dri-drivers                        \
  xorg-x11-xbitmaps                       \
  && yum clean all

RUN yum update -y && yum install -y       \
  nano                                    \
  vim                                     \
  wget                                    \
  && yum clean all

RUN echo 'buildbot ALL=(ALL) NOPASSWD:SETENV: /usr/local/bin/singularity, /bin/chown' >> /etc/sudoers

{% include 'common/Dockerfile.j2' %}
