FROM centos:centos7

RUN yum install -y epel-release           \
  && yum update -y                        \
  && yum clean all

RUN yum groups mark install "Development Tools" \
  && yum groups mark convert "Development Tools" \
  && yum groupinstall -y "Development Tools" \
  && yum clean all

# Base dependencies
RUN yum update -y && yum install -y       \
  Lmod                                    \
  bash-completion                         \
  cmake                                   \
  curl                                    \
  git                                     \
  libarchive-devel                        \
  libnl3                                  \
  libnl3-devel                            \
  libuuid-devel                           \
  openssh                                 \
  openssl-devel                           \
  python                                  \
  python-devel                            \
  python36                                \
  python36-devel                          \
  rust                                    \
  rsync                                   \
  shadow-utils                            \
  squashfs-tools                          \
  sudo                                    \
  tcl                                     \
  unzip                                   \
  wget                                    \
  which                                   \
  && yum clean all

# Install singularity

RUN yum update -y && yum install -y       \
  singularity                             \
  && yum clean all

# Add mellanox ib stack

RUN yum update -y && yum install -y       \
  pciutils                                \
  numactl-libs                            \
  gtk2                                    \
  atk                                     \
  cairo                                   \
  tcsh                                    \
  lsof                                    \
  libmnl                                  \
  ethtool                                 \
  tk                                      \
  && yum clean all

ENV RPMS_DIR=/tmp/rpms

ARG MLNX_VERSION=4.9-3.1.5.0-rhel7.9-x86_64

COPY ./extra_rpms/MLNX_OFED_LINUX-${MLNX_VERSION} $RPMS_DIR

ARG KERNEL=3.10.0-1160.42.2

RUN yum update -y && yum install -y       \
  kernel-devel-${KERNEL}.el7.x86_64       \
  && yum clean all

RUN cd ${RPMS_DIR} &&              \
  yes | ./mlnxofedinstall          \
      --force                      \
      --add-kernel-support         \
      --without-fw-update          \
      --skip-repo                  \
      --kernel ${KERNEL}           \
      --kernel-sources /usr/src/kernels/${KERNEL}.el7.x86_64 \
      --without-rshim              \
  && rm -r ${RPMS_DIR}


# Add Open HPC slurm

RUN yum install -y https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm

RUN yum update -y && yum install -y       \
  hwloc-libs                              \
  munge-ohpc                              \
  && yum clean all


ARG SLURM_VERSION=21.08.0-4.1
ARG OHPC_VERSION=1.3.8.1

COPY ./extra_rpms/slurm $RPMS_DIR
RUN cd ${RPMS_DIR} && yum localinstall -y                                                 \
  ./slurm-contribs-ohpc-${SLURM_VERSION}.ohpc.${OHPC_VERSION}.x86_64.rpm        \
  ./slurm-devel-ohpc-${SLURM_VERSION}.ohpc.${OHPC_VERSION}.x86_64.rpm           \
  ./slurm-example-configs-ohpc-${SLURM_VERSION}.ohpc.${OHPC_VERSION}.x86_64.rpm \
  ./slurm-libpmi-ohpc-${SLURM_VERSION}.ohpc.${OHPC_VERSION}.x86_64.rpm          \
  ./slurm-ohpc-${SLURM_VERSION}.ohpc.${OHPC_VERSION}.x86_64.rpm                 \
  ./slurm-pam_slurm-ohpc-${SLURM_VERSION}.ohpc.${OHPC_VERSION}.x86_64.rpm       \
  ./slurm-perlapi-ohpc-${SLURM_VERSION}.ohpc.${OHPC_VERSION}.x86_64.rpm         \
  ./slurm-slurmd-ohpc-${SLURM_VERSION}.ohpc.${OHPC_VERSION}.x86_64.rpm          \
  && yum clean all && rm -r ${RPMS_DIR}

# Add other packages

RUN yum update -y && yum install -y       \
  mesa-dri-drivers                        \
  xorg-x11-xbitmaps                       \
  && yum clean all

RUN yum update -y && yum install -y       \
  nano                                    \
  vim                                     \
  wget                                    \
  && yum clean all

RUN echo 'buildbot ALL=(ALL) NOPASSWD:SETENV: /usr/bin/singularity, /bin/chown' >> /etc/sudoers

{% include 'common/Dockerfile.j2' %}
