build_environment_repository: https://github.com/AaltoScienceIT/science-build-environment.git
science_build_rules_repository: https://github.com/AaltoScienceIT/science-build-rules.git
build_folder: /tmp/science-build-environment
compose_project_name: example-ci
buildbot_master:
  image: aaltoscienceit/scibuilder-master:latest
  fqdn: 'localhost'
  gitlab_hook_secret: 'hook_secret'
  worker_password: 'workerpass'
  worker_port: 9989
  web_port: 8010
  timeout: 7200
  worker_uid: builder uid here
auths:
  ssh:
    config_file: configs/ci-local/ssh_config
    known_hosts_file: configs/ci-local/ssh_known_hosts
buildbot_db: 
  postgres_password: postgrespass
builds:
  singularity:
    enabled: False
  spack:
    enabled: True
target_workers:
  - name: centos
    image: aaltoscienceit/scibuilder-worker:fgci-centos7
    spack:
      target_path: /share/apps/spack/production
      url: https://github.com/AaltoScienceIT/spack.git
      branch: develop
