build_environment_repository: git@version.aalto.fi:AaltoScienceIT/science-build-environment.git
science_build_rules_repository: git@github.com:AaltoScienceIT/science-build-rules.git
build_folder: /tmp/science-build-environment
buildbot_master:
  image: registry.cs.aalto.fi/aaltoscienceit/scibuilder-master:latest
  gitlab_hook_secret: 'hook_secret'
  worker_password: 'workerpass'
  worker_port: 9989
  web_url: 'http://localhost:8010/'
  web_port: 8010
  timeout: 7200
  worker_uid: 123123
buildbot_db: 
  postgres_password: postgrespass
builds:
  singularity:
    enabled: False
    enable_portus_hook: True
  spack:
    enabled: True
  registry_clone:
    enabled: False
compose_project_name: triton-ci
target_workers:
  - name: centos-test
    image: registry.cs.aalto.fi/aaltoscienceit/scibuilder-worker:centos-test
  - name: centos-test-dev
    image: registry.cs.aalto.fi/aaltoscienceit/scibuilder-worker:centos-test-dev
skip_rules: ['clone_environment_repository']
