config:
  install_path: /cvmfs/fgi.csc.fi/apps/el7/aalto/singularity/software
  module_path: /cvmfs/fgi.csc.fi/apps/el7/aalto/singularity/modules
  source_cache: /cache/singularity/source
  tmpdir: /tmp/singularity
  build_stage: /cache/singularity/stage
  wrapper_path: /cvmfs/fgi.csc.fi/apps/el7/aalto/singularity_wrapper
  remove_after_update: True
  sudo: False
  fakeroot: True
  debug: False
