config:
  install_path: /m/work/modules/automatic/anaconda/envs/aalto-ubuntu1804-generic/software
  module_path: /m/work/modules/automatic/anaconda/envs/aalto-ubuntu1804-generic/modules
  source_cache: /cache/anaconda
  tmpdir: /tmp/anaconda
  remove_after_update: True
