config:
  install_path: /share/apps/anaconda-ci/fgci-centos7-upstream/software
  module_path: /share/apps/anaconda-ci/fgci-centos7-upstream/modules
  source_cache: /cache/anaconda
  tmpdir: /tmp/anaconda
  remove_after_update: True
