compilers:
  - name: 'gcc'
    version: 4.8.5
    system_compiler: true
    flags:
      cflags: -O2 -g
      cxxflags: -O2 -g
      fflags: -O2 -g
  - name: 'gcc'
    version: 9.2.0
    variants:
      - '+piclibs'
    dependencies:
      - '%gcc@4.8.5'
    flags:
      cflags: -O2 -g -march=haswell -ftree-vectorize
      cxxflags: -O2 -g -march=haswell -ftree-vectorize
      fflags: -O2 -g -march=haswell -ftree-vectorize
  - name: 'intel-parallel-studio'
    version: 'cluster.2019.3'
    licenses:
      - 'license.lic'
    flags:
      cflags: -O2 -g -march=haswell
      cxxflags: -O2 -g -march=haswell
      fflags: -O2 -g -march=haswell
packages:
  - name: 'chapel'
    version: 1.19.0
  - name: 'cuda'
    version: 10.1.243
  - name: 'go'
    version: 1.12.8
  - name: 'openmpi'
    version: 3.1.4
  - name: 'python'
    version: 3.7.4
  - name: 'r'
    version: 3.6.1
  - name: 'py-gpaw'
    version: 1.3.0
    variants:
      - '+fftw'
      - '+mpi'
      - '+scalapack'
  - name: 'py-gpaw'
    version: 19.8.1
    variants:
      - '+fftw'
      - '+mpi'
      - '+scalapack'
  - name: 'upcxx'
    version: 2019.3.2
