FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

USER root

RUN apt-get update &&                     \
  apt-get -y upgrade &&                   \
  apt-get -y install -q                   \
  apt-transport-https                     \
  bash                                    \
  bash-completion                         \
  ca-certificates                         \
  cmake                                   \
  curl                                    \
  git                                     \
  gosu                                    \
  grep                                    \
  libarchive-dev                          \
  libnl-3-200                             \
  libnl-3-dev                             \
  libssh-4                                \
  libssh2-1                               \
  libssh2-1-dev                           \
  libssl-dev                              \
  libvshadow-utils                        \
  lmod                                    \
  openssh-client                          \
  python                                  \
  python-dev                              \
  python-jinja2                           \
  python-pip                              \
  python-yaml                             \
  python3                                 \
  python3-coloredlogs                     \
  python3-dev                             \
  python3-jinja2                          \
  python3-jsonschema                      \
  python3-pip                             \
  python3-requests                        \
  python3-sh                              \
  python3-yaml                            \
  rsync                                   \
  software-properties-common              \
  squashfs-tools                          \
  ssh                                     \
  sudo                                    \
  tcl                                     \
  unzip                                   \
  uuid-dev                                \
  wget                                    \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update &&                     \
  apt-get -y install -q                   \
  singularity-container                   \
  libgl1-mesa-dri                         \
  xbitmaps                                \
  && rm -rf /var/lib/apt/lists/*

RUN echo 'buildbot ALL=(ALL) NOPASSWD:SETENV: /usr/bin/singularity, /bin/chown' >> /etc/sudoers

{% include 'common/Dockerfile.j2' %}
